---
- name: Import elasticsearch gpg key
  environment: proxy_env
  rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Add repos /etc/yum.repos.d/elasticsearch.repo
  template:
       src: "etc/yum.repos.d/repo.template.j2"
       dest: "/etc/yum.repos.d/elasticsearch.repo"
       owner: root
       group: root
       mode: 0644
  with_items:
       - { name: "elasticsearch-{{ kibana_elasticsearch_version }}",
           baseurl: "http://packages.elasticsearch.org/elasticsearch/{{ kibana_elasticsearch_version }}/centos",
           gpgcheck: 1,
           gpgkey: 'http://packages.elasticsearch.org/GPG-KEY-elasticsearch',
           enabled: 1 }

- name: install java-1.8.0-openjdk
  yum: name=java-1.8.0-openjdk state=installed

- name: install elasticsearch
  yum: name=elasticsearch state=installed

- name: ensure service elasticsearch started
  service:
       name: elasticsearch
       state: started
       enabled: yes

- name: elasticsearch iptables rules
  lineinfile:
    dest: /etc/sysconfig/iptables
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "^-A INPUT -j REJECT"
  with_items:
    - { regexp: "^-A INPUT -p tcp --dport {{ elasticsearch_port }} -s 0.0.0.0/0 -j ACCEPT$", line: "-A INPUT -p tcp --dport {{ elasticsearch_port }} -s 0.0.0.0/0 -j ACCEPT" }
  notify:
        - iptables-reload
